name: blog-post

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  blog-post:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: sync blog posts
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -ahvz --include-from=".github/rsync_include.txt" --exclude-from=".github/rsync_exclude.txt"
        path: .
        remote_path: /home/${{ secrets.SSH_USERNAME }}/temp
        remote_host: ${{ secrets.SSH_HOST }}
        remote_port: ${{ secrets.SSH_PORT }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
